theme: jekyll-theme-cayman
title: New England Library Carpentry
description: A group of New England library workers who are building confidence in tech tools and tech literacy for public librarians
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
baseurl: ""
